

INSERT INTO COUNTRY_MASTER (COUNTRY_ID ,COUNTRY_NAME) VALUES (1,'INDIA'),(2,'USA');
INSERT INTO STATE_MASTER (STATE_ID , COUNTRY_ID ,STATE_NAME) VALUES (1, 1,'MAHARASHTRA');
INSERT INTO STATE_MASTER (STATE_ID , COUNTRY_ID ,STATE_NAME) VALUES (2, 1,'kARNATAKA');
INSERT INTO STATE_MASTER (STATE_ID , COUNTRY_ID ,STATE_NAME) VALUES (3, 2,'NEW YORK');
INSERT INTO STATE_MASTER (STATE_ID , COUNTRY_ID ,STATE_NAME) VALUES (4, 2,'NEW JERSY');
INSERT INTO CITY_MASTER (CITY_ID , STATE_ID ,CITY_NAME) VALUES (1, 1,'PUNE');
INSERT INTO CITY_MASTER (CITY_ID , STATE_ID ,CITY_NAME) VALUES (2, 1,'MUMBAI');
INSERT INTO CITY_MASTER (CITY_ID , STATE_ID ,CITY_NAME) VALUES (3, 2,'BANGLURU');
INSERT INTO CITY_MASTER (CITY_ID , STATE_ID ,CITY_NAME) VALUES (4, 2,'MYSORE');
INSERT INTO CITY_MASTER (CITY_ID , STATE_ID ,CITY_NAME) VALUES (5, 3,'Rochester');
INSERT INTO CITY_MASTER (CITY_ID , STATE_ID ,CITY_NAME) VALUES (6, 3,'Ithaca');
INSERT INTO CITY_MASTER (CITY_ID , STATE_ID ,CITY_NAME) VALUES (7, 4,'Elizabeth');
INSERT INTO CITY_MASTER (CITY_ID , STATE_ID ,CITY_NAME) VALUES (8, 4,'Princeton');